name: CMakeClang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup msbuild
      if: inputs.configuration != 'CMake'
      uses: microsoft/setup-msbuild@v1

    - name: Setup VCPKG
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        .\vcpkg install 

    - name: init_submodules
      run: git submodule update --init --recursive

    - name: Build
      shell: cmd
      run: |
        mkdir build
        cd build
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DPPC_BUILD_PPC_TESTS=True -DCMAKE_SYSTEM_NAME="Generic" -DCMAKE_TOOLCHAIN_FILE=D:/a/dingusppc/dingusppc/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build . --config Release 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DingusPPC-WIN32-MSVC
        path: ${{github.workspace}}/build
