name: CMakeWIN32

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_DEFAULT_TRIPLET: x64-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup msbuild
      if: inputs.configuration != 'CMake'
      uses: microsoft/setup-msbuild@v1

    - name: Setup VCPKG
      run: |
         vcpkg integrate install
         vcpkg install 

    - name: init_submodules
      run: git submodule update --init --recursive
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      if: inputs.configuration == 'CMake'
      id: cmake
      shell: cmd
      run: |
        mkdir build
        cd build
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -DCMAKE_BUILD_TYPE=Release -DPPC_BUILD_PPC_TESTS=True -DCMAKE_SYSTEM_NAME="Generic" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_CXX_FLAGS="/EHsc" .. 
        cmake --build . --config Release 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DingusPPC-WIN32-MSVC
        path: ${{github.workspace}}/build
